#!/bin/bash

#arcman - views man pages in custom directories (see man page)
# (Cross platform, BASh script)
#Copyright (C) 2015-2017  Arc676/Alessandro Vinciguerra <alesvinciguerra@gmail.com>

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation (version 3)

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

printUsage(){
	echo Usage: arcman program_name
	echo Use arcman arcman for more information about this utility
}

if [ $# -ne 1 ]; then
	printUsage
	exit 1
fi

conffile=$HOME/.arcutillib/arcman.conf

if [ ! -f "$conffile" ]; then
	echo Error: configuration file not found
	exit 1
fi

if [ $1 = "list" ]; then
	while read path; do
		ls $path;
	done < $conffile
else
	found=0
	while read path; do
		if [ -f "$path/$1" ]; then
			man "$path/$1" 2> /dev/null
			found=1
			break
		fi
	done < $conffile
	if [ $found -eq 0 ]; then
		echo Man page not found.
		exit 1
	fi
fi
