#!/usr/bin/osascript

#listen4keyword - toggle macOS's 'listen for keyword' speakable items function
# (Mac only, AppleScript file)
#Copyright (C) 2016-2017  Arc676/Alessandro Vinciguerra <alesvinciguerra@gmail.com>

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation (version 3)

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

tell application "System Preferences"
	reveal anchor "SpeakableItems" of pane id "com.apple.preference.universalaccess"
end tell
tell application "System Events" to tell application process "System Preferences"
	click checkbox 1 of window 1
end tell
tell application "System Preferences" to quit
